"""add lorebook_entry and message citations

Revision ID: d32e9401e82e
Revises: f4aa2532a1d0
Create Date: 2026-10-07 21:47:05.811470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32e9401e82e'
down_revision: Union[str, None] = 'f4aa2532a1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lorebook_entry',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='冗余: 创建者(权限校验免join)'),
    sa.Column('keywords', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_character', 'lorebook_entry', ['character_id', 'enabled'], unique=False)
    op.add_column('message', sa.Column('citations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'citations')
    op.drop_index('idx_character', table_name='lorebook_entry')
    op.drop_table('lorebook_entry')
    # ### end Alembic commands ###
