"""baseline schema

Revision ID: f4aa2532a1d0
Revises: 
Create Date: 2026-10-07 18:12:22.814272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4aa2532a1d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model_code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user', 'ai_model', ['user_id', 'is_default'], unique=False)
    op.create_table('character',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('intro', sa.String(length=200), nullable=False, comment='一句话介绍'),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('greeting', sa.String(length=500), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_type', sa.String(length=20), server_default='USER', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('chat_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_creator', 'character', ['creator_id'], unique=False)
    op.create_index('idx_square', 'character', ['status', 'creator_type'], unique=False)
    op.create_table('character_favorite',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'character_id', name='uk_user_char')
    )
    op.create_index('idx_user', 'character_favorite', ['user_id'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=True, comment='会话级模型覆盖'),
    sa.Column('kb_id', sa.BigInteger(), nullable=True, comment='绑定的知识库 (RAG)'),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_preview', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_last', 'conversation', ['user_id', 'last_message_at'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('doc_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_document',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kb_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PROCESSING', nullable=False),
    sa.Column('error_msg', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb', 'knowledge_document', ['kb_id'], unique=False)
    op.create_index('idx_user', 'knowledge_document', ['user_id'], unique=False)
    op.create_table('memory',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('memory_key', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('importance', sa.String(length=20), server_default='MEDIUM', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('source_conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inject', 'memory', ['user_id', 'character_id', 'status', 'importance'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_message_id', sa.BigInteger(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('client_message_id', sa.String(length=64), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=False, comment='USER/ASSISTANT/SYSTEM'),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='COMPLETED', nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('model_code', sa.String(length=50), nullable=True),
    sa.Column('feedback', sa.String(length=20), server_default='NONE', nullable=False),
    sa.Column('regenerate_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_message_id', name='uk_client_msg')
    )
    op.create_index('idx_conv', 'message', ['conversation_id', 'id'], unique=False)
    op.create_index('idx_feedback', 'message', ['feedback'], unique=False)
    op.create_index('idx_user_created', 'message', ['user_id', 'created_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False, comment='BCrypt密文'),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='USER', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uk_username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index('idx_user_created', table_name='message')
    op.drop_index('idx_feedback', table_name='message')
    op.drop_index('idx_conv', table_name='message')
    op.drop_table('message')
    op.drop_index('idx_inject', table_name='memory')
    op.drop_table('memory')
    op.drop_index('idx_user', table_name='knowledge_document')
    op.drop_index('idx_kb', table_name='knowledge_document')
    op.drop_table('knowledge_document')
    op.drop_table('knowledge_base')
    op.drop_index('idx_user_last', table_name='conversation')
    op.drop_table('conversation')
    op.drop_index('idx_user', table_name='character_favorite')
    op.drop_table('character_favorite')
    op.drop_index('idx_square', table_name='character')
    op.drop_index('idx_creator', table_name='character')
    op.drop_table('character')
    op.drop_index('idx_user', table_name='ai_model')
    op.drop_table('ai_model')
    # ### end Alembic commands ###
